name: demes-binder

dependencies:
  - python=3.9
  - pip
  - pip:
    - -r file:requirements/minimal.txt
    # Install demes from current directory.
    - .
    # Needed to open myst-markdown files as notebooks.
    - jupytext
